<?php

return [
    [
        "title" => 'Villa al Mare',
        "description" => 'Splendida Villa al Mare con vista sulla statale',
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "mq" => 100,
        "is_visible" => true,
        "price" => 300.00,
    ],
    [
        "title" => 'Chalet in montagna',
        "description" => 'Splendido Chalet in montagna  con vista sulla discarica',
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "mq" => 80,
        "is_visible" => true,
        "price" => 200.00,
    ],
    [
        "title" => 'Appartamento in collina',
        "description" => 'Splendida Villa al Mare con vista sulla statale',
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "mq" => 100,
        "is_visible" => true,
        "price" => 300.00,
    ],
    [
        "title" => 'Baita in montagna',
        "description" => 'Splendido Chalet in montagna  con vista sulla discarica',
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "mq" => 80,
        "is_visible" => true,
        "price" => 200.00,
    ],
    [
        "title" => 'Fattoria',
        "description" => 'Splendida Villa al Mare con vista sulla statale',
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "mq" => 100,
        "is_visible" => true,
        "price" => 300.00,
    ],
    [
        "title" => 'Igloo in Antartide',
        "description" => 'Splendido Chalet in montagna  con vista sulla discarica',
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "mq" => 80,
        "is_visible" => true,
        "price" => 200.00,
    ],
    [
        "title" => 'Castello medievale',
        "description" => 'Splendida Villa al Mare con vista sulla statale',
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "mq" => 100,
        "is_visible" => true,
        "price" => 300.00,
    ],
    [
        "title" => 'Tenda Quechua',
        "description" => 'Splendido Chalet in montagna  con vista sulla discarica',
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "mq" => 80,
        "is_visible" => true,
        "price" => 200.00,
    ],
];
