<?php

return [
    [
        "title" => 'Villa al Mare',
        "description" => 'Splendida Villa al Mare con vista sulla statale',
        "address" => 'via tasso 12 27100 Pavia',
        "longitude" => '49.1256',
        "latitude" => '11.2486',
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "mq" => 100,
        "is_visible" => true,
        "price" => 300.00,
    ],
    [
        "title" => 'Villa al Mare',
        "description" => 'Splendida Villa al Mare con vista sulla statale',
        "address" => 'via tasso 12 27100 Pavia',
        "longitude" => '49.1256',
        "latitude" => '11.2486',
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "mq" => 100,
        "is_visible" => true,
        "price" => 300.00,
    ],
    [
        "title" => 'Villa al Mare',
        "description" => 'Splendida Villa al Mare con vista sulla statale',
        "address" => 'via tasso 12 27100 Pavia',
        "longitude" => '49.1256',
        "latitude" => '11.2486',
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "mq" => 100,
        "is_visible" => true,
        "price" => 300.00,
    ],
    [
        "title" => 'Villa al Mare',
        "description" => 'Splendida Villa al Mare con vista sulla statale',
        "address" => 'via tasso 12 27100 Pavia',
        "longitude" => '49.1256',
        "latitude" => '11.2486',
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "mq" => 100,
        "is_visible" => true,
        "price" => 300.00,
    ],
    [
        "title" => 'Villa al Mare',
        "description" => 'Splendida Villa al Mare con vista sulla statale',
        "address" => 'via tasso 12 27100 Pavia',
        "longitude" => '49.1256',
        "latitude" => '11.2486',
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "mq" => 100,
        "is_visible" => true,
        "price" => 300.00,
    ],
    [
        "title" => 'Villa al Mare',
        "description" => 'Splendida Villa al Mare con vista sulla statale',
        "address" => 'via tasso 12 27100 Pavia',
        "longitude" => '49.1256',
        "latitude" => '11.2486',
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "mq" => 100,
        "is_visible" => true,
        "price" => 300.00,
    ],
    [
        "title" => 'Villa al Mare',
        "description" => 'Splendida Villa al Mare con vista sulla statale',
        "address" => 'via tasso 12 27100 Pavia',
        "longitude" => '49.1256',
        "latitude" => '11.2486',
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "mq" => 100,
        "is_visible" => true,
        "price" => 300.00,
    ],
    [
        "title" => 'Villa al Mare',
        "description" => 'Splendida Villa al Mare con vista sulla statale',
        "address" => 'via tasso 12 27100 Pavia',
        "longitude" => '49.1256',
        "latitude" => '11.2486',
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "mq" => 100,
        "is_visible" => true,
        "price" => 300.00,
    ],
    [
        "title" => 'Villa al Mare',
        "description" => 'Splendida Villa al Mare con vista sulla statale',
        "address" => 'via tasso 12 27100 Pavia',
        "longitude" => '49.1256',
        "latitude" => '11.2486',
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "mq" => 100,
        "is_visible" => true,
        "price" => 300.00,
    ],
    [
        "title" => 'Villa al Mare',
        "description" => 'Splendida Villa al Mare con vista sulla statale',
        "address" => 'via tasso 12 27100 Pavia',
        "longitude" => '49.1256',
        "latitude" => '11.2486',
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "mq" => 100,
        "is_visible" => true,
        "price" => 300.00,
    ],
    [
        "title" => 'Villa al Mare',
        "description" => 'Splendida Villa al Mare con vista sulla statale',
        "address" => 'via tasso 12 27100 Pavia',
        "longitude" => '49.1256',
        "latitude" => '11.2486',
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "mq" => 100,
        "is_visible" => true,
        "price" => 300.00,
    ],
    [
        "title" => 'Villa al Mare',
        "description" => 'Splendida Villa al Mare con vista sulla statale',
        "address" => 'via tasso 12 27100 Pavia',
        "longitude" => '49.1256',
        "latitude" => '11.2486',
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "mq" => 100,
        "is_visible" => true,
        "price" => 300.00,
    ],
    [
        "title" => 'Villa al Mare',
        "description" => 'Splendida Villa al Mare con vista sulla statale',
        "address" => 'via tasso 12 27100 Pavia',
        "longitude" => '49.1256',
        "latitude" => '11.2486',
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "mq" => 100,
        "is_visible" => true,
        "price" => 300.00,
    ],


];
